2025-06-27 04:47:44,237 - database - DEBUG - Creating new database session
2025-06-27 04:47:44,241 - database - DEBUG - Creating new database session
2025-06-27 04:47:44,250 - database - ERROR - Error in database session: 500: An error occurred while refreshing token.
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\api\v1\endpoints\users.py", line 310, in refresh_access_token
     raise HTTPException(
    ...<3 lines>...
    )
fastapi.exceptions.HTTPException: 401: Invalid or expired refresh token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\database\session.py", line 65, in get_db
    yield session
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\app\api\v1\endpoints\users.py", line 360, in refresh_access_token
    raise HTTPException(
    ...<2 lines>...
    )
fastapi.exceptions.HTTPException: 500: An error occurred while refreshing token.
2025-06-27 04:47:44,256 - database - INFO - Session rolled back due to error
2025-06-27 04:47:44,257 - database - DEBUG - Closing database session
2025-06-27 04:47:46,092 - database - DEBUG - Database session used successfully
2025-06-27 04:47:46,092 - database - DEBUG - Closing database session
2025-06-27 04:47:48,367 - database - DEBUG - Creating new database session
2025-06-27 04:47:48,664 - database - DEBUG - Database session used successfully
2025-06-27 04:47:48,676 - database - DEBUG - Closing database session
2025-06-27 04:47:49,916 - database - DEBUG - Creating new database session
2025-06-27 04:47:50,085 - database - DEBUG - Database session used successfully
2025-06-27 04:47:50,086 - database - DEBUG - Closing database session
2025-06-27 04:47:50,151 - database - DEBUG - Creating new database session
2025-06-27 04:47:50,439 - database - DEBUG - Database session used successfully
2025-06-27 04:47:50,446 - database - DEBUG - Closing database session
2025-06-27 04:47:50,526 - database - DEBUG - Creating new database session
2025-06-27 04:47:50,583 - database - DEBUG - Database session used successfully
2025-06-27 04:47:50,584 - database - DEBUG - Closing database session
2025-06-27 04:47:50,588 - database - DEBUG - Creating new database session
2025-06-27 04:47:52,565 - database - DEBUG - Database session used successfully
2025-06-27 04:47:52,569 - database - DEBUG - Closing database session
2025-06-27 04:47:52,615 - database - DEBUG - Creating new database session
2025-06-27 04:47:52,983 - database - DEBUG - Creating new database session
2025-06-27 04:47:55,316 - database - DEBUG - Database session used successfully
2025-06-27 04:47:55,319 - database - DEBUG - Closing database session
2025-06-27 04:47:55,411 - database - DEBUG - Creating new database session
2025-06-27 04:47:55,477 - database - DEBUG - Database session used successfully
2025-06-27 04:47:55,482 - database - DEBUG - Closing database session
2025-06-27 04:49:04,606 - database - DEBUG - Creating new database session
2025-06-27 04:49:04,619 - database - DEBUG - Database session used successfully
2025-06-27 04:49:04,619 - database - DEBUG - Closing database session
2025-06-27 04:49:20,061 - database - DEBUG - Creating new database session
2025-06-27 04:49:20,074 - database - ERROR - Error in database session: 500: An error occurred while refreshing token.
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\api\v1\endpoints\users.py", line 310, in refresh_access_token
     raise HTTPException(
    ...<3 lines>...
    )
fastapi.exceptions.HTTPException: 401: Invalid or expired refresh token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\database\session.py", line 65, in get_db
    yield session
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\app\api\v1\endpoints\users.py", line 360, in refresh_access_token
    raise HTTPException(
    ...<2 lines>...
    )
fastapi.exceptions.HTTPException: 500: An error occurred while refreshing token.
2025-06-27 04:49:20,079 - database - INFO - Session rolled back due to error
2025-06-27 04:49:20,080 - database - DEBUG - Closing database session
2025-06-27 04:49:43,381 - database - DEBUG - Database session used successfully
2025-06-27 04:49:43,396 - database - DEBUG - Closing database session
2025-06-27 05:03:35,745 - database - DEBUG - Creating new database session
2025-06-27 05:03:38,881 - database - DEBUG - Creating new database session
2025-06-27 05:03:38,898 - database - ERROR - Error in database session: 500: An error occurred while refreshing token.
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\api\v1\endpoints\users.py", line 310, in refresh_access_token
     raise HTTPException(
    ...<3 lines>...
    )
fastapi.exceptions.HTTPException: 401: Invalid or expired refresh token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\database\session.py", line 65, in get_db
    yield session
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\app\api\v1\endpoints\users.py", line 360, in refresh_access_token
    raise HTTPException(
    ...<2 lines>...
    )
fastapi.exceptions.HTTPException: 500: An error occurred while refreshing token.
2025-06-27 05:03:38,907 - database - INFO - Session rolled back due to error
2025-06-27 05:03:38,908 - database - DEBUG - Closing database session
2025-06-27 05:03:40,428 - database - DEBUG - Database session used successfully
2025-06-27 05:03:40,429 - database - DEBUG - Closing database session
2025-06-27 05:04:09,851 - database - DEBUG - Creating new database session
2025-06-27 05:04:10,152 - database - DEBUG - Database session used successfully
2025-06-27 05:04:10,153 - database - DEBUG - Closing database session
2025-06-27 05:04:11,343 - database - DEBUG - Creating new database session
2025-06-27 05:04:11,367 - database - DEBUG - Database session used successfully
2025-06-27 05:04:11,368 - database - DEBUG - Closing database session
2025-06-27 05:04:11,407 - database - DEBUG - Creating new database session
2025-06-27 05:04:11,430 - database - DEBUG - Database session used successfully
2025-06-27 05:04:11,430 - database - DEBUG - Closing database session
2025-06-27 05:04:11,436 - database - DEBUG - Creating new database session
2025-06-27 05:04:11,498 - database - DEBUG - Creating new database session
2025-06-27 05:04:11,578 - database - DEBUG - Database session used successfully
2025-06-27 05:04:11,579 - database - DEBUG - Closing database session
2025-06-27 05:04:12,778 - database - DEBUG - Database session used successfully
2025-06-27 05:04:12,782 - database - DEBUG - Closing database session
2025-06-27 05:04:12,820 - database - DEBUG - Creating new database session
2025-06-27 05:04:13,291 - database - DEBUG - Creating new database session
2025-06-27 05:04:15,929 - database - DEBUG - Database session used successfully
2025-06-27 05:04:15,930 - database - DEBUG - Closing database session
2025-06-27 05:04:17,001 - database - DEBUG - Creating new database session
2025-06-27 05:04:17,111 - database - DEBUG - Database session used successfully
2025-06-27 05:04:17,115 - database - DEBUG - Closing database session
2025-06-27 05:05:26,348 - database - DEBUG - Database session used successfully
2025-06-27 05:05:26,349 - database - DEBUG - Closing database session
2025-06-27 05:05:48,744 - database - DEBUG - Creating new database session
2025-06-27 05:06:02,532 - database - DEBUG - Database session used successfully
2025-06-27 05:06:02,532 - database - DEBUG - Closing database session
2025-06-27 05:06:03,236 - database - DEBUG - Creating new database session
2025-06-27 05:06:03,258 - database - DEBUG - Database session used successfully
2025-06-27 05:06:03,258 - database - DEBUG - Closing database session
2025-06-27 05:06:03,270 - database - DEBUG - Creating new database session
2025-06-27 05:06:03,292 - database - DEBUG - Database session used successfully
2025-06-27 05:06:03,292 - database - DEBUG - Closing database session
2025-06-27 05:06:03,303 - database - DEBUG - Creating new database session
2025-06-27 05:06:03,314 - database - DEBUG - Database session used successfully
2025-06-27 05:06:03,315 - database - DEBUG - Closing database session
2025-06-27 05:06:03,735 - database - DEBUG - Creating new database session
2025-06-27 05:06:03,997 - database - DEBUG - Creating new database session
2025-06-27 05:06:04,024 - database - DEBUG - Creating new database session
2025-06-27 05:06:04,135 - database - DEBUG - Database session used successfully
2025-06-27 05:06:04,136 - database - DEBUG - Closing database session
2025-06-27 05:06:04,860 - database - DEBUG - Creating new database session
2025-06-27 05:06:04,894 - database - DEBUG - Database session used successfully
2025-06-27 05:06:04,895 - database - DEBUG - Closing database session
2025-06-27 05:06:04,975 - database - DEBUG - Database session used successfully
2025-06-27 05:06:04,976 - database - DEBUG - Closing database session
2025-06-27 05:06:05,002 - database - DEBUG - Creating new database session
2025-06-27 05:06:05,039 - database - DEBUG - Database session used successfully
2025-06-27 05:06:05,040 - database - DEBUG - Closing database session
2025-06-27 05:06:05,075 - database - DEBUG - Creating new database session
2025-06-27 05:06:05,094 - database - DEBUG - Database session used successfully
2025-06-27 05:06:05,094 - database - DEBUG - Closing database session
2025-06-27 05:06:05,200 - database - DEBUG - Creating new database session
2025-06-27 05:06:05,209 - database - DEBUG - Database session used successfully
2025-06-27 05:06:05,209 - database - DEBUG - Closing database session
2025-06-27 05:06:05,672 - database - DEBUG - Database session used successfully
2025-06-27 05:06:05,672 - database - DEBUG - Closing database session
2025-06-27 05:06:05,680 - database - DEBUG - Creating new database session
2025-06-27 05:06:06,038 - database - DEBUG - Creating new database session
2025-06-27 05:06:06,350 - database - DEBUG - Database session used successfully
2025-06-27 05:06:06,358 - database - DEBUG - Closing database session
2025-06-27 05:06:06,401 - database - DEBUG - Creating new database session
2025-06-27 05:06:06,474 - database - DEBUG - Database session used successfully
2025-06-27 05:06:06,475 - database - DEBUG - Closing database session
